name: nerfenv
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - pip
  - cuda-toolkit=11.8
  - pip:
    - natsort
    - PyMcubes
    - pyglet==1.5.27
    - wheel
    - tqdm
    - numpy
    - matplotlib
    - pillow
    - imageio
    - open3d
    - torch == 2.0.0
    - torchvision == 0.15.1
    - "--extra-index-url https://download.pytorch.org/whl/cu118"
    - tensorboard